manager/src/Model/User/Entity/Role.php
<?php

namespace App\Model\User\Entity;

class Role
{
    public const USER = 'ROLE_USER';

    private $name;

    public function __construct($name)
    {
        if(!$this->roleExists($name)) {
            throw new \InvalidArgumentException('Given role not found.');
        }

        $this->name = $name;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function isUser(): bool
    {
        if($this->name === self::USER) {
            return true;
        }

        return false;
    }

    public static function roleExists(String $role): bool
    {
        if(in_array($role, static::getRoleList())) {
            return true;
        }

        return false;
    }

    public static function getRoleList(): array
    {
        return [
            self::USER,
        ];
    }
}

manager/src/Controller/Profile/HomeController.php
<?php

namespace App\Controller\Profile;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/profile", name="profile.")
 */
class HomeController extends AbstractController
{
    /**
     * @Route("", name="home")
     * @return Response
     */
    public function home(): Response
    {
        return $this->render('profile/home.html.twig');
    }
}

manager/src/Controller/Profile/PasswordChangeController.php
<?php

namespace App\Controller\Profile;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Model\User\UseCase\ChangePassword;
use App\Model\User\UseCase\ChangePassword\Request\Handler as RequestHandler;
use App\Model\User\UseCase\ChangePassword\Confirm\Handler as ConfirmHandler;

/**
 * @Route("/profile/password_change", name="profile.password_change.")
 */
class PasswordChangeController extends AbstractController
{
    /**
     * @var RequestHandler
     */
    private $requestHandler;

    /**
     * @var ConfirmHandler
     */
    private $confirmHandler;

    public function __construct(RequestHandler $requestHandler, ConfirmHandler $confirmHandler)
    {
        $this->requestHandler = $requestHandler;
        $this->confirmHandler = $confirmHandler;
    }

    /**
     * @Route("", name="request")
     * @param Request $request
     * @return Response
     */
    public function request(Request $request): Response
    {
        $command = new ChangePassword\Request\Command();
        $command->login = $this->getUser()->getLogin();
        $form = $this->createForm(ChangePassword\Request\Form::class, $command);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            try {
                $this->requestHandler->handle($command);
                $this->addFlash('success', 'Check your email to confirm password change.');
            } catch (\DomainException $e) {
                $this->addFlash('error', $e->getMessage());
            }
            return $this->redirectToRoute('profile.password_change.request');
        }

        return $this->render('profile/password_change.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/{token}", name="confirm")
     * @param string $token
     * @return Response
     */
    public function confirm(string $token): Response
    {
        $command = new ChangePassword\Confirm\Command();
        $command->login = $this->getUser()->getLogin();
        $command->token = $token;

        try {
            $this->confirmHandler->handle($command);
            $this->addFlash('success', 'Password is successfully changed.');
        } catch (\DomainException $e) {
            $this->addFlash('error', $e->getMessage());
        }

        return $this->redirectToRoute('profile.password_change.request');
    }
}

manager/templates/profile/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home{% endblock %}

{% block body %}
    {% for status in app.flashes('status') %}
        {{ status }}
    {% endfor %}
    {% for error in app.flashes('error') %}
        {{ error }}
    {% endfor %}
    {% for success in app.flashes('success') %}
        {{ success }}
    {% endfor %}

    {% if app.user %}
        <div class="mb-3">
            You are logged in as {{ app.user.username }}, <a href="{{ path('app_logout') }}">Logout</a>
        </div>
    {% endif %}
{% endblock %}

manager/templates/profile/password_change.html.twig
{% extends 'base.html.twig' %}

{% block title %}Password change{% endblock %}

{% block body %}
    {% for status in app.flashes('status') %}
        {{ status }}
    {% endfor %}
    {% for error in app.flashes('error') %}
        {{ error }}
    {% endfor %}
    {% for success in app.flashes('success') %}
        {{ success }}
    {% endfor %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    <input type="submit" value="Send">
    {{ form_end(form) }}
{% endblock %}